SELECT * FROM USUARIO
SELECT * FROM EMPRESA

SELECT * FROM ROLES


--INSERT INTO ROLES VALUES ('DIRECTIVO')
--INSERT INTO ROLES VALUES ('ADMINISTRADOR')
--INSERT INTO ROLES VALUES ('PROFESOR')
--INSERT INTO ROLES VALUES ('REPRESENTANTE')
--INSERT INTO ROLES VALUES ('ROOT')

--INSERT INTO EMPRESA VALUES ('4F0EF2D3-A470-4B2D-B2EF-A9B8A8EE1777','EMC Software','V-11346727','efrainmejiasc@hotmail.com','04244133677','Valencia-Venezuela',GetDate(),GetDate(),1)
--INSERT INTO USUARIO VALUES ('efrainmejiasc@hotmail.com',2,'Efrain','Mejias','efrain','ZWZyYWlubWVqaWFzY0Bob3RtYWlsLmNvbTEyMzQ=','ZWZyYWluMTIzNA==',GetDate(),1,4)